enum E_ACCOUNT_CATEGORIES {
  EMPLOYEE = 'EMPLOYEE',
  SERVICE_SHOP = 'SERVICE_SHOP',
  DELIVERY_SERVICE = 'DELIVERY_SERVICE',
  FINANCER = 'FINANCER',
  BROKER = 'BROKER',
}


enum E_PRIMARY_LEDGERS {
   EMPLOYEE = 'salary payables',
   SERVICE_SHOP = 'Customer',
   DELIVERY_SERVICE = '',
   FINANCER = '',
   BROKER = 'Payables',
}

export { E_ACCOUNT_CATEGORIES, E_PRIMARY_LEDGERS };
